export class LanguageUtils {
  static translations = {
    // Navigation
    'X Bot Manager': 'X Bot Yöneticisi',
    'Account Settings': 'Hesap Ayarları',
    'News Sources': 'Haber Kaynakları', 
    'Found Contents': 'Bulunan İçerikler',
    'AI Settings': 'Yapay Zeka Ayarları',
    'Statistics': 'İstatistikler',
    'System Logs': 'Sistem Kayıtları',
    
    // Account Settings
    'Source Account (Account A)': 'Kaynak Hesap (A Hesabı)',
    'Target Account (Account B)': 'Hedef Hesap (B Hesabı)',
    'Save Account Settings': 'Hesap Ayarlarını Kaydet',
    'Configure your source and target X accounts': 'Kaynak ve hedef X hesaplarınızı yapılandırın',
    
    // News Sources
    'Add news sources to monitor': 'İzlenecek haber kaynakları ekleyin',
    'Select RSS News Sources': 'RSS Haber Kaynaklarını Seçin',
    
    // Found Contents
    'Automatically discovered tweets and news articles': 'Otomatik olarak keşfedilen tweetler ve haber makaleleri',
    'View Original': 'Orijinalini Görüntüle',
    'Approve': 'Onayla',
    'Reject': 'Reddet',
    'Post Now': 'Şimdi Paylaş',
    'Delete': 'Sil',
    
    // AI Settings
    'Configure AI analysis for content filtering': 'İçerik filtreleme için Yapay Zeka analizini yapılandırın',
    'Save AI Settings': 'AI Ayarlarını Kaydet',
    'Add English Keywords': 'İngilizce Anahtar Kelimeler Ekle',
    'Add Turkish Keywords': 'Türkçe Anahtar Kelimeler Ekle',
    
    // Statistics
    'View statistics and analytics': 'İstatistikleri ve analizleri görüntüleyin',
    'Refresh Statistics': 'İstatistikleri Yenile',
    'Generate Report': 'Rapor Oluştur',
    'Reset Stats': 'İstatistikleri Sıfırla',
    
    // System Logs
    'System logs and activity': 'Sistem kayıtları ve aktivite',
    'Export JSON': 'JSON\'a Aktar',
    'Clear Old': 'Eskileri Temizle',
    'Clear All': 'Hepsini Temizle',
    
    // Common
    'Please sign in to access the dashboard': 'Panoya erişmek için lütfen giriş yapın',
    'Loading...': 'Yükleniyor...',
    'Save': 'Kaydet',
    'Test': 'Test',
    'Active': 'Aktif',
    'Pending': 'Beklemede',
    'Approved': 'Onaylandı',
    'Posted': 'Paylaşıldı',
    'Rejected': 'Reddedildi',
    'Sign Out': 'Çıkış Yap',
    'Never': 'Hiç',
    'Just now': 'Şimdi',
    'ago': 'önce',
    'Soon': 'Yakında',
    'Any moment': 'Her an',
    'in': '',
    'minutes': 'dakika',
    'minute': 'dakika',
    'min': 'dk',
    'Items': 'Öğe',
    'Last:': 'Son:',
    'Next:': 'Sonraki:',
    'Auto-scan:': 'Otomatik tarama:',
    'every': 'her',
    'Content items processed': 'İşlenen içerik öğeleri',
    'Automatically approved': 'Otomatik olarak onaylandı',
    'Successfully shared': 'Başarıyla paylaşıldı',
    'Filtered out': 'Filtrelendi',
    'Efficiency': 'Verimlilik',
    'Posted/Scanned ratio': 'Paylaşılan/Taranan oranı',
    'AI Approval Rate': 'AI Onay Oranı',
    'Auto-approved content': 'Otomatik onaylanan içerik',
    'Rejection Rate': 'Reddetme Oranı',
    'Filtered content': 'Filtrelenen içerik',
    'Success Rate': 'Başarı Oranı',
    'Overall performance': 'Genel performans',
    'Last Content Scan': 'Son İçerik Taraması',
    'Last Tweet Posted': 'Son Tweet Paylaşımı',
    'Last News Posted': 'Son Haber Paylaşımı',
    'Next Scheduled Scan': 'Sonraki Planlanan Tarama',
    'Not scheduled': 'Planlanmadı',
    'System Uptime': 'Sistem Çalışma Süresi',
    'Continuous operation': 'Kesintisiz çalışma',
    'Last Refresh': 'Son Yenileme',
    'User:': 'Kullanıcı:',
    'Data Scope:': 'Veri Kapsamı:',
    'User-specific statistics': 'Kullanıcıya özel istatistikler',
    'Real-time Updates:': 'Gerçek Zamanlı Güncellemeler:',
    'Enabled': 'Etkin',
    'Disabled': 'Devre Dışı',
    'Total Operations:': 'Toplam İşlem:',
    'Please sign in to view statistics and analytics.': 'İstatistikleri ve analizleri görüntülemek için lütfen giriş yapın.',
    'Statistics Overview:': 'İstatistiklere Genel Bakış:',
    'Please sign in to view system logs and activity.': 'Sistem günlüklerini ve etkinliği görüntülemek için lütfen giriş yapın.',
    'Logs Configuration:': 'Günlük Yapılandırması:',
    'Total Logs:': 'Toplam Günlük:',
    'Current Filter:': 'Geçerli Filtre:',
    'Display Limit:': 'Görüntüleme Limiti:',
    'logs': 'günlük',
    'Auto-refresh:': 'Otomatik yenileme:',
    'Context': 'Bağlam',
    'Welcome to X Bot Manager': 'X Bot Yöneticisine Hoş Geldiniz',
    'Sign in to manage your Twitter automation': 'Twitter otomasyonunuzu yönetmek için giriş yapın',
    'Sign in with Google': 'Google ile Giriş Yap',
    'Note:': 'Not:',
    'A popup will open for Google sign-in': 'Google girişi için bir açılır pencere açılacak',
    'Please allow popups for this site if prompted': 'İstenirse lütfen bu site için açılır pencerelere izin verin',
    
    // Status Messages
    '✅ AI settings saved for:': '✅ AI ayarları kaydedildi:',
    '❌ Error loading AI settings:': '❌ AI ayarları yüklenirken hata:',
    '⚠️ Please sign in to load settings': '⚠️ Lütfen ayarları yüklemek için giriş yapın',
    '👤 Loaded AI settings for:': '👤 AI ayarları yüklendi:',
    '👤 Signed in as:': '👤 Giriş yapıldı:',
    ' - Configure and save AI settings.': ' - AI ayarlarını yapılandırın ve kaydedin.',
    'Saving AI settings...': 'AI ayarları kaydediliyor...',
    '❌ Error saving AI settings:': '❌ AI ayarları kaydedilirken hata:',
    '✅ Added Turkish keywords': '✅ Türkçe anahtar kelimeler eklendi',
    '✅ Added English keywords': '✅ İngilizce anahtar kelimeler eklendi',
    'Content containing these keywords will be automatically filtered and shared': 'Bu anahtar kelimeleri içeren içerikler otomatik olarak filtrelenecek ve paylaşılacak',
    'This text will be prepended to all shared content': 'Bu metin tüm paylaşılan içeriklerin önüne eklenecek',
    'Analyze emotional tone of content before sharing': 'Paylaşmadan önce içeriğin duygusal tonunu analiz edin',
    'Manual approval required before content is posted': 'İçerik paylaşılmadan önce manuel onay gerekli',
    'Free Keyword Matching': 'Ücretsiz Anahtar Kelime Eşleştirme',
    
    // Found Contents
    '⚠️ Add news sources to start automatic scanning': '⚠️ Otomatik taramayı başlatmak için haber kaynakları ekleyin',
    '✅ Found ': '✅ Bulundu ',
    ' new contents': ' yeni içerik',
    '❌ Scan failed: ': '❌ Tarama başarısız: ',
    '❌ Scan error: ': '❌ Tarama hatası: ',
    '✅ Content approved': '✅ İçerik onaylandı',
    '❌ Error approving content': '❌ İçerik onaylanırken hata',
    '🚀 Posting content...': '🚀 İçerik paylaşılıyor...',
    'Account settings not found': 'Hesap ayarları bulunamadı',
    '✅ Content posted successfully!': '✅ İçerik başarıyla paylaşıldı!',
    '❌ Error posting: ': '❌ Paylaşım hatası: ',
    '❌ Content rejected': '❌ İçerik reddedildi',
    '❌ Error rejecting content': '❌ İçerik reddedilirken hata',
    '🗑️ Content deleted': '🗑️ İçerik silindi',
    '❌ Error deleting content': '❌ İçerik silinirken hata',
    'Please sign in to post content': 'Lütfen içerik paylaşmak için giriş yapın',
    'No contents found matching the current filter.': 'Geçerli filtreyle eşleşen içerik bulunamadı.',
    'Please sign in to see your contents.': 'İçeriklerinizi görmek için lütfen giriş yapın.',
    'To get started:': 'Başlamak için:',
    'Configure your X account settings': 'X hesap ayarlarınızı yapılandırın',
    'Add news sources to monitor': 'İzlenecek haber kaynakları ekleyin',
    'Set up AI keywords for filtering': 'Filtreleme için AI anahtar kelimelerini ayarlayın',
    'Choose your preferred scan frequency in News Sources': 'Haber Kaynakları\'nda tercih ettiğiniz tarama sıklığını seçin',
    'The system will automatically scan every': 'Sistem otomatik olarak her',
    'AI Analysis:': 'AI Analizi:',
    'confidence': 'güven',
    'Keywords:': 'Anahtar Kelimeler:',
    'Posting...': 'Paylaşılıyor...',
    'Please sign in to view and manage found contents.': 'Bulunan içerikleri görüntülemek ve yönetmek için lütfen giriş yapın.',
    
    // Statistics
    '⚠️ Please sign in to view statistics': '⚠️ Lütfen istatistikleri görüntülemek için giriş yapın',
    '📊 Live statistics for: ': '📊 Canlı istatistikler: ',
    '❌ Error loading statistics: ': '❌ İstatistikler yüklenirken hata: ',
    '🔄 Refreshing statistics...': '🔄 İstatistikler yenileniyor...',
    '✅ Statistics refreshed successfully': '✅ İstatistikler başarıyla yenilendi',
    '❌ Error refreshing statistics: ': '❌ İstatistikler yenilenirken hata: ',
    '📈 Generating detailed report...': '📈 Detaylı rapor oluşturuluyor...',
    '✅ Report generated successfully (check console)': '✅ Rapor başarıyla oluşturuldu (konsolu kontrol edin)',
    'Are you sure you want to reset all statistics? This action cannot be undone.': 'Tüm istatistikleri sıfırlamak istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    '🔄 Resetting statistics...': '🔄 İstatistikler sıfırlanıyor...',
    '✅ Statistics reset successfully': '✅ İstatistikler başarıyla sıfırlandı',
    '❌ Error resetting statistics: ': '❌ İstatistikler sıfırlanırken hata: ',
    'Invalid date': 'Geçersiz tarih',
    
    // System Logs
    '⚠️ Please sign in to view system logs': '⚠️ Lütfen sistem günlüklerini görüntülemek için giriş yapın',
    '📋 Loaded ': '📋 Yüklendi ',
    ' logs for: ': ' günlük: ',
    '❌ Error loading logs: ': '❌ Günlükler yüklenirken hata: ',
    '📥 Preparing log export...': '📥 Günlük dışa aktarımı hazırlanıyor...',
    '✅ Logs exported successfully': '✅ Günlükler başarıyla dışa aktarıldı',
    '❌ Error exporting logs: ': '❌ Günlükler dışa aktarılırken hata: ',
    'Are you sure you want to clear all logs? This action cannot be undone.': 'Tüm günlükleri temizlemek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    '🗑️ Clearing logs...': '🗑️ Günlükler temizleniyor...',
    '✅ Logs cleared successfully': '✅ Günlükler başarıyla temizlendi',
    '❌ Error clearing logs: ': '❌ Günlükler temizlenirken hata: ',
    'Are you sure you want to clear logs older than ': 'Şu tarihten eski günlükleri temizlemek istediğinizden emin misiniz: ',
    ' days?': ' gün?',
    '🗑️ Clearing logs older than ': '🗑️ Şu tarihten eski günlükler temizleniyor: ',
    ' days...': ' gün...',
    'ℹ️ No logs found older than the specified period': 'ℹ️ Belirtilen dönemden eski günlük bulunamadı',
    '✅ Cleared ': '✅ Temizlendi ',
    ' logs older than ': ' günlük, şu tarihten eski: ',
    ' days': ' gün',
    '❌ Error clearing old logs: ': '❌ Eski günlükler temizlenirken hata: ',
    '🔄 Refreshing logs...': '🔄 Günlükler yenileniyor...',
    '✅ Logs refreshed': '✅ Günlükler yenilendi',
    'Please sign in to refresh logs': 'Lütfen günlükleri yenilemek için giriş yapın',
    'Total': 'Toplam',
    'Info': 'Bilgi',
    'Success': 'Başarı',
    'Warning': 'Uyarı',
    'Error': 'Hata',
    'Debug': 'Hata Ayıklama',
    'All Logs': 'Tüm Günlükler',
    'No logs found yet. System activity will appear here.': 'Henüz günlük bulunamadı. Sistem etkinliği burada görünecek.',
    'No logs found matching the current filter.': 'Geçerli filtreyle eşleşen günlük bulunamadı.',
    'Please sign in to view system logs.': 'Sistem günlüklerini görüntülemek için lütfen giriş yapın.',
    
    // News Sources
    'Configure RSS news sources and automatic scanning frequency. RSS feeds work without CORS issues.': 'RSS haber kaynaklarını ve otomatik tarama sıklığını yapılandırın. RSS beslemeleri CORS sorunu olmadan çalışır.',
    'Language / Dil': 'Dil / Language',
    'Auto-Scan Frequency': 'Otomatik Tarama Sıklığı',
    'System will automatically scan RSS feeds for new content': 'Sistem RSS beslemelerini yeni içerik için otomatik olarak tarayacak',
    'Choose which news sources to monitor. RSS feeds provide real content without CORS errors.': 'Hangi haber kaynaklarının izleneceğini seçin. RSS beslemeleri CORS hataları olmadan gerçek içerik sağlar.',
    '🔄 Reset to Defaults': '🔄 Varsayılanlara Sıfırla',
    'Save Settings': 'Ayarları Kaydet',
    'RSS Feed Status:': 'RSS Besleme Durumu:',
    'Sources Selected:': 'Seçilen Kaynaklar:',
    'Scan Frequency:': 'Tarama Sıklığı:',
    'Every': 'Her',
    'Content Type:': 'İçerik Türü:',
    'Real RSS News Feeds': 'Gerçek RSS Haber Beslemeleri',
    '5 minutes': '5 dakika',
    '10 minutes': '10 dakika', 
    '15 minutes': '15 dakika',
    '30 minutes': '30 dakika',
    '1 hour': '1 saat',
    
    // Account Settings
    '❌ Firebase not initialized': '❌ Firebase başlatılmadı',
    '📥 Loaded account settings:': '📥 Hesap ayarları yüklendi:',
    '❌ Please sign in to save settings': '❌ Lütfen ayarları kaydetmek için giriş yapın',
    '❌ Please fill in Source and Target account usernames': '❌ Lütfen Kaynak ve Hedef hesap kullanıcı adlarını doldurun',
    'Saving...': 'Kaydediliyor...',
    '✅ Settings saved for:': '✅ Ayarlar kaydedildi:',
    '🚀 Initialize Firestore': '🚀 Firestore\'u Başlat',
    '🔍 Test Connection': '🔍 Bağlantıyı Test Et',
    'Firestore Status:': 'Firestore Durumu:',
    'User Email:': 'Kullanıcı E-posta:',
    'Auto-creation:': 'Otomatik oluşturma:',
    'Will be created on first save': 'İlk kaydetmede oluşturulacak'
  };

  static getText(key, language = 'english') {
    if (language === 'turkish' && this.translations[key]) {
      return this.translations[key];
    }
    return key;
  }

  static detectUserLanguage() {
    const browserLang = navigator.language || navigator.userLanguage;
    return browserLang.startsWith('tr') ? 'turkish' : 'english';
  }
}